<?php

/**
 * SystemPress The Functions
 * @package SystemPress
 * @author G.L. Walker
 * @since 0.0.1
 *
 */
// Exit if accessed directly.
defined('ABSPATH') || exit;

// Display current year
function sp_year_shortcode()
{
	$year = date_i18n('Y');
	return $year;
}
add_shortcode('year', 'sp_year_shortcode');

// Display site title
function sp_site_title_shortcode()
{
	return get_bloginfo('name');
}
add_shortcode('site_title', 'sp_site_title_shortcode');

if (!function_exists('sp_id')) {
	/**
	 * Retrieve the post ID.
	 *
	 * This function attempts to retrieve the actual post ID by first checking the
	 * current post ID. If it's not available, it will attempt to grab the post ID
	 * from the URL by using `url_to_postid()` as a fallback.
	 *
	 * @return int|null The post ID or null if not found.
	 */
	function sp_id(): ?int
	{
		global $post;
		global $wp_query;

		// Get the post ID using the WordPress function.
		$post_id = get_the_ID();

		// If the post ID is not available, try to get it from the URL.
		if (!$post_id) {
			$sp_id = str_replace(array('/', '.php', '?pg='), '', $_SERVER['REQUEST_URI']);
			$post_id = url_to_postid($sp_id);
		}

		// Return the post ID.
		return $post_id ?: null;
	}
}

if (!function_exists('sp_get_class_name')) {
	/**
	 * Retrieve the `className` attribute from a block.
	 *
	 * This function ensures that a valid string is always returned.
	 * If the `className` attribute is not set, an empty string is returned
	 * instead of null to prevent issues with functions that require a string.
	 *
	 * @param array $block The block array.
	 * @return string The class name or an empty string if not set.
	 */
	function sp_get_class_name(array $block): string
	{
		return $block['attrs']['className'] ?? '';
	}
}

if (!function_exists('sp_get_background_color')) {
	/**
	 * Retrieve the `backgroundColor` attribute from a block.
	 *
	 * This function ensures a valid string is returned. If the `backgroundColor`
	 * attribute is not set, an empty string is returned instead of null to prevent
	 * issues with functions that require a string input.
	 *
	 * @param array $block The block array.
	 * @return string The background color or an empty string if not set.
	 */
	function sp_get_background_color(array $block): string
	{
		return $block['attrs']['backgroundColor'] ?? '';
	}
}

if (!function_exists('sp_get_custom_setting')) {
	/**
	 * Retrieves a custom setting by its slug from the global theme settings.
	 *
	 * This function fetches the custom settings from the global WordPress settings,
	 * specifically looking in the 'settings' array for any custom settings defined
	 * in the theme's JSON configuration. If the setting with the provided slug exists,
	 * it returns its value. If the setting is not found, it returns null.
	 *
	 * @param string $slug The slug of the custom setting to retrieve.
	 *
	 * @return mixed The value of the custom setting if it exists, or null if not found.
	 */
	function sp_get_custom_setting($slug)
	{

		$custom_settings = wp_get_global_settings()['custom'] ?? [];

		// Debugging: Output the custom settings
		//error_log('Custom Settings: ' . print_r($custom_settings, true));

		return $custom_settings[$slug] ?? null; // Returns the value or null if not found
	}
}

if (!function_exists('sp_do_block_action')) {
	/**
	 * Execute a WordPress action hook inside block content.
	 *
	 * This function captures the output of a WordPress action hook
	 * executed within a block. It uses output buffering to store
	 * the content produced by `do_action()` and returns it as a string.
	 *
	 * @param string $hook The name of the action hook to execute.
	 * @return string The content generated by the action hook.
	 */

	function sp_do_block_action(string $hook = ''): string
	{
		// Start output buffering to capture action hook output.
		ob_start();
		do_action($hook);
		$block_action = ob_get_contents();
		ob_end_clean();

		// Return the captured content.
		return $block_action;
	}
}

if (!function_exists('sp_action_hook')) {
	/**
	 * Add hooks using the core/separator block.
	 *
	 * This function modifies the content of the core/separator block by
	 * adding hooks dynamically. The separator block should have the trigger
	 * class `sp-action-hook` followed by the desired hook name.
	 * This works in conjunction with the `sp_do_block_action()` function.
	 *
	 * @param string $block_content The original block content.
	 * @param array $block The block attributes.
	 * @return string The modified block content with the action hook applied.
	 */
	add_filter('render_block_core/separator', 'sp_action_hook', null, 2);

	function sp_action_hook(string $block_content, array $block): string
	{
		$class_name = sp_get_class_name($block);
		if (!$class_name) {
			return $block_content;
		}

		// Exit if the class does not contain the trigger class 'sp-action-hook'.
		if (!str_contains($class_name, 'sp-action-hook')) {
			return $block_content;
		}

		// Extract the action hook name from the class name (after 'sp-action-hook ').
		$action = explode('sp-action-hook ', $class_name)[1] ?? '';

		// If an action is found, execute it and replace the block content.
		if ($action && 'sp-action-hook ' . $action === sp_get_class_name($block)) {
			$block_content = sp_do_block_action($action);
		}

		return $block_content;
	}
}

if (!function_exists('sp_do_comments_template')) {
	/**
	 * Add the comments template to block-based pages.
	 *
	 * This function checks if a page or post is singular (a single post or page) and if comments are open
	 * or there are existing comments. If so, it loads the comment template part using the `block_template_part()` function.
	 *
	 * @since 1.0.0
	 */
	add_action('sp_hook_end_single', 'sp_do_comments_template', 15);
	add_action('sp_hook_end_page', 'sp_do_comments_template', 15);

	function sp_do_comments_template(): void
	{
		// Check if we're on a singular post or page.
		if (is_singular()) {
			// If comments are open or there are existing comments, load the comments template part.
			if (comments_open() || get_comments_number() != '0') {
				block_template_part('part-comments');
			}
		}
	}
}

if (!function_exists('sp_register_pattern_categories')) {
	/**
	 * Register custom block pattern categories.
	 *
	 * @since 1.0
	 * @return void
	 */
	function sp_register_pattern_categories()
	{
		$categories = array(
			'carousel' => array(
				'label'       => _x('Carousels', 'Block pattern category', 'systempress'),
			),
			'bootstrap-components' => array(
				'label'       => _x('BS Components', 'Block pattern category', 'systempress'),
			),
			// Add more categories as needed
		);

		foreach ($categories as $slug => $args) {
			register_block_pattern_category($slug, $args);
		}
	}

	add_action('init', 'sp_register_pattern_categories');
}

if (!function_exists('sp_register_block_category')) {
	/**
	 * Register custom block category for SystemPress blocks.
	 *
	 * @since 1.0
	 * @param array $categories List of existing block categories.
	 * @param WP_Post $post Current post object.
	 * @return array Modified list of block categories.
	 */
	function sp_register_block_category($categories, $post)
	{
		$category = array(
			'slug'  => 'systempress-blocks',
			'title' => 'SystemPress Blocks',
		);

		// Check if category already exists
		$existing_slugs = array_column($categories, 'slug');

		if (in_array($category['slug'], $existing_slugs)) {
			return $categories; // Bail early if the category exists
		}

		// Add category at the top
		array_unshift($categories, $category);

		return $categories;
	}

	// Hook into 'block_categories_all' to add the category
	add_filter('block_categories_all', 'sp_register_block_category', 10, 2);
}

if (!function_exists('sp_replace_it')) {
	/**
	 * Check if a string exists and sanitize the replacement.
	 *
	 * This function checks if a given value exists in a string. If it does, it replaces it
	 * with a new value and sanitizes the result using `sanitize_text_field()`.
	 *
	 * @param string $value The string to find and replace in the `$string`.
	 * @param string $newval The value to replace `$value` with.
	 * @param string $string The string in which to perform the replacement.
	 *
	 * @return string|null The sanitized string after replacement, or null if no replacement occurred.
	 */
	function sp_replace_it(string $value, string $newval, string $string): ?string
	{
		// Exit early if the value is empty or not provided.
		if (empty($value)) {
			return null;
		}

		// Perform the replacement and sanitize the result.
		$css = str_contains($string, $value) ? sanitize_text_field(str_replace($value, $newval, $string)) : $string;

		// Return the sanitized string or the original string if no replacement was made.
		return $css;
	}
}

if (!function_exists('sp_replace_block_content')) {
	/**
	 * Replace content in the block's rendered HTML.
	 *
	 * @param string $block_content The block's rendered content.
	 * @param string $search The search string.
	 * @param string $replace The replacement string.
	 * @param int $limit The limit of replacements. Default is 1.
	 * @return string The updated block content.
	 */
	/*
	function sp_replace_block_content(string $block_content, string $search, string $replace, int $limit = 1): string
	{
		return preg_replace('/' . preg_quote($search, '/') . '/', $replace, $block_content, $limit);
	}
	*/
	function sp_replace_block_content(string $block_content, string $search, string $replace, int $limit = 1): string
	{
		$pattern = '/' . preg_quote($search, '/') . '/';
		$result = preg_replace($pattern, $replace, $block_content, $limit);
		return is_string($result) ? $result : $block_content;
	}
}
